"""
meals_data.py

Contains the list of available meals,
each with nutritional values and associated suitable meal times.
"""

MEALS = [
    {"name": "Double Cheeseburger with Fries", "calories": 1100, "protein": 35, "carbs": 45, "fat": 55, "satiety": 0.8, "meal_times": ["dinner"]},
    {"name": "Chocolate Croissant", "calories": 400, "protein": 5, "carbs": 40, "fat": 25, "satiety": 0.3, "meal_times": ["breakfast", "snack"]},
    {"name": "Sweetened Iced Coffee", "calories": 250, "protein": 2, "carbs": 35, "fat": 10, "satiety": 0.1, "meal_times": ["snack"]},
    {"name": "Cornflakes with Milk", "calories": 250, "protein": 8, "carbs": 40, "fat": 5, "satiety": 0.5, "meal_times": ["breakfast"]},
    {"name": "Greek Yogurt with Nuts", "calories": 180, "protein": 15, "carbs": 8, "fat": 8, "satiety": 0.6, "meal_times": ["breakfast", "snack"]},
    {"name": "Oatmeal with Peanut Butter and Banana", "calories": 400, "protein": 14, "carbs": 50, "fat": 12, "satiety": 0.75, "meal_times": ["breakfast"]},
    {"name": "Tuna Salad with Quinoa", "calories": 300, "protein": 30, "carbs": 20, "fat": 8, "satiety": 0.9, "meal_times": ["dinner"]},
    {"name": "Whole Grain Pizza with Light Cheese and Veggies", "calories": 600, "protein": 28, "carbs": 50, "fat": 20, "satiety": 0.8, "meal_times": ["dinner"]},
    {"name": "Toast with Avocado and Egg", "calories": 350, "protein": 18, "carbs": 25, "fat": 15, "satiety": 0.75, "meal_times": ["dinner"]},
    {"name": "Handful of Almonds", "calories": 200, "protein": 7, "carbs": 8, "fat": 18, "satiety": 0.4, "meal_times": ["snack"]},
    {"name": "Dark Chocolate (4 Squares)", "calories": 150, "protein": 2, "carbs": 15, "fat": 10, "satiety": 0.3, "meal_times": ["snack"]},
    {"name": "Protein Bar", "calories": 220, "protein": 20, "carbs": 15, "fat": 7, "satiety": 0.6, "meal_times": ["snack"]},
    {"name": "Banana", "calories": 90, "protein": 1, "carbs": 23, "fat": 0, "satiety": 0.6, "meal_times": ["snack"]},
    {"name": "Yogurt Protein", "calories": 130, "protein": 20, "carbs": 6, "fat": 1, "satiety": 0.6, "meal_times": ["snack"]},
    {"name": "Shakshuka with Bread", "calories": 450, "protein": 17, "carbs": 35, "fat": 22, "satiety": 0.8, "meal_times": ["breakfast"]},
    {"name": "Pancakes with Syrup", "calories": 500, "protein": 8, "carbs": 60, "fat": 20, "satiety": 0.5, "meal_times": ["breakfast"]},
    {"name": "French Toast", "calories": 420, "protein": 12, "carbs": 35, "fat": 20, "satiety": 0.6, "meal_times": ["breakfast"]},
    {"name": "Sabich Pita", "calories": 550, "protein": 16, "carbs": 45, "fat": 25, "satiety": 0.7, "meal_times": ["lunch"]},
    {"name": "Falafel in Pita with Tahini", "calories": 700, "protein": 20, "carbs": 50, "fat": 30, "satiety": 0.8, "meal_times": ["lunch"]},
    {"name": "Spaghetti Carbonara", "calories": 750, "protein": 25, "carbs": 60, "fat": 30, "satiety": 0.85, "meal_times": ["dinner"]},
    {"name": "Egg Salad Sandwich", "calories": 350, "protein": 15, "carbs": 30, "fat": 18, "satiety": 0.7, "meal_times": ["lunch", "snack"]},
    {"name": "Granola with Yogurt", "calories": 400, "protein": 12, "carbs": 40, "fat": 15, "satiety": 0.6, "meal_times": ["breakfast", "snack"]},
    {"name": "Avocado Toast", "calories": 300, "protein": 8, "carbs": 25, "fat": 18, "satiety": 0.6, "meal_times": ["breakfast", "snack"]},
    {"name": "Orange Juice", "calories": 120, "protein": 2, "carbs": 28, "fat": 0, "satiety": 0.2, "meal_times": ["snack"]},
    {"name": "Ice Cream Cup", "calories": 350, "protein": 5, "carbs": 40, "fat": 20, "satiety": 0.4, "meal_times": ["snack"]},
    {"name": "Omelette with Cottage Cheese and Vegetables", "calories": 300, "protein": 20, "carbs": 10, "fat": 10, "satiety": 0.8, "meal_times": ["breakfast"]},
    {"name": "Schnitzel with Mashed Potatoes", "calories": 850, "protein": 35, "carbs": 50, "fat": 40, "satiety": 0.9, "meal_times": ["dinner"]},
    {"name": "Pita with Zaatar and Olive Oil", "calories": 480, "protein": 7, "carbs": 45, "fat": 28, "satiety": 0.6, "meal_times": ["breakfast", "snack"]},
    {"name": "Couscous with Chickpeas", "calories": 500, "protein": 18, "carbs": 55, "fat": 10, "satiety": 0.85, "meal_times": ["lunch"]},
    {"name": "Matbucha and Challah", "calories": 450, "protein": 6, "carbs": 40, "fat": 25, "satiety": 0.7, "meal_times": ["lunch", "snack"]},
    {"name": "Green Smoothie", "calories": 180, "protein": 8, "carbs": 20, "fat": 5, "satiety": 0.5, "meal_times": ["snack"]},
    {"name": "Pastry with Cheese", "calories": 600, "protein": 12, "carbs": 45, "fat": 35, "satiety": 0.5, "meal_times": ["breakfast", "snack"]},
    {"name": "Cheese Toast", "calories": 400, "protein": 14, "carbs": 30, "fat": 20, "satiety": 0.6, "meal_times": ["snack", "lunch"]},
    {"name": "Rice Cakes with Peanut Butter", "calories": 250, "protein": 8, "carbs": 25, "fat": 14, "satiety": 0.4, "meal_times": ["snack"]},
    {"name": "Cereal Bar", "calories": 180, "protein": 4, "carbs": 25, "fat": 6, "satiety": 0.3, "meal_times": ["snack"]},
    {"name": "Grilled Halloumi Salad", "calories": 420, "protein": 20, "carbs": 15, "fat": 28, "satiety": 0.75, "meal_times": ["lunch", "dinner"]},
    {"name": "Steak with Baked Potato", "calories": 800, "protein": 45, "carbs": 40, "fat": 35, "satiety": 0.95, "meal_times": ["dinner"]},
    {"name": "Turkey Wrap", "calories": 450, "protein": 30, "carbs": 35, "fat": 15, "satiety": 0.8, "meal_times": ["lunch"]},
    {"name": "Burekas with Egg", "calories": 500, "protein": 10, "carbs": 35, "fat": 30, "satiety": 0.6, "meal_times": ["breakfast"]},
    {"name": "Chicken Breast with Rice and Broccoli", "calories": 550, "protein": 40, "carbs": 40, "fat": 15, "satiety": 0.95, "meal_times": ["lunch"]},
    {"name": "Tofu Stir-fry with Vegetables and Brown Rice", "calories": 500, "protein": 25, "carbs": 35, "fat": 18, "satiety": 0.85, "meal_times": ["lunch"]},
    {"name": "Baked Salmon with Couscous and Vegetables", "calories": 650, "protein": 35, "carbs": 40, "fat": 22, "satiety": 0.9, "meal_times": ["lunch"]},
    {"name": "Lean Beef Burger with Whole Wheat Bun and Veggies", "calories": 700, "protein": 35, "carbs": 35, "fat": 25, "satiety": 0.85, "meal_times": ["dinner"]},
    {"name": "Caprese Salad", "calories": 300, "protein": 10, "carbs": 10, "fat": 20, "satiety": 0.6, "meal_times": ["snack", "lunch"]},
    {"name": "Grilled Chicken with Sweet Potato and Greens", "calories": 600, "protein": 40, "carbs": 45, "fat": 15, "satiety": 0.95, "meal_times": ["lunch"]},
    {"name": "Tuna Sandwich", "calories": 400, "protein": 22, "carbs": 35, "fat": 15, "satiety": 0.7, "meal_times": ["lunch"]},
    {"name": "Roasted Vegetables with Hummus", "calories": 350, "protein": 10, "carbs": 30, "fat": 20, "satiety": 0.7, "meal_times": ["dinner"]},
    {"name": "Milkshake (Large)", "calories": 650, "protein": 8, "carbs": 60, "fat": 35, "satiety": 0.4, "meal_times": ["snack"]},
    {"name": "Veggie Soup with Bread", "calories": 300, "protein": 8, "carbs": 30, "fat": 10, "satiety": 0.65, "meal_times": ["lunch", "dinner"]},
    {"name": "Grilled Turkey Breast with Quinoa Salad", "calories": 500, "protein": 40, "carbs": 30, "fat": 10, "satiety": 0.85, "meal_times": ["lunch"]},
    {"name": "Muesli with Fruit", "calories": 350, "protein": 10, "carbs": 40, "fat": 12, "satiety": 0.6, "meal_times": ["breakfast"]}
]
